file_format: "1"
id: choc_corne
name: choc_corne
type: shield
url: https://github.com/jeudcastaneda/zmk-config-choc_corne
requires: [nice_nano_v2]
features:
  - keys
siblings:
  - choc_corne_left
  - choc_corne_right